"""Adjusted-series spot-check against snapshotted Yahoo Finance references.

Yahoo's Close (auto_adjust=False) is split/bonus-adjusted but not
dividend-adjusted -- the same convention as our adj_close -- so levels are
directly comparable. Yahoo's splits series is an independent record of
split/bonus events to check our declared-feed factors against. Fixtures are
generated by scripts/make_spotcheck_fixture.py; the test needs no network.
"""

import csv
from datetime import date, timedelta
from pathlib import Path

import polars as pl
import pytest

from artha.config import load_settings

SETTINGS = load_settings()
PANEL_PATH = SETTINGS.curated_dir / "panel.parquet"
FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "reference"

pytestmark = pytest.mark.skipif(
    not PANEL_PATH.exists(), reason="curated zone not built on this machine"
)

# Rights adjustments legitimately differ between vendors (observed ex-date
# gap here vs theoretical ex-rights price at Yahoo) by ~1-2% per event.
PRICE_REL_TOL = 0.025
FACTOR_REL_TOL = 0.01
EX_DATE_SLACK_DAYS = 5

# Documented Yahoo data deficiencies (verified against NSE declared feed and
# our price-continuity checks on 2026-07-12):
# - WIPRO: Yahoo never adjusted the 2013-04-09 Wipro Enterprises demerger
#   (our observed-gap factor 0.9069); its pre-demerger levels are ~9% high.
YAHOO_PRICE_EXCEPTIONS: dict[str, date] = {"WIPRO": date(2013, 4, 9)}  # skip samples before
# - Yahoo lists only the split leg of same-day bonus+split events; our
#   combined factors are validated by the price-level test instead.
YAHOO_SPLIT_EXCEPTIONS = {
    ("BAJFINANCE", date(2016, 9, 8)),  # bonus 1:1 + split 10->2 (ours 0.1)
    ("BAJFINANCE", date(2025, 6, 16)),  # bonus 4:1 + split 2->1 (ours 0.1)
    ("TITAN", date(2011, 6, 23)),  # bonus 1:1 + split 10->1 (ours 0.05)
}


def _read_fixture(name: str) -> list[dict[str, str]]:
    with (FIXTURES / name).open(newline="") as f:
        return list(csv.DictReader(f))


@pytest.fixture(scope="module")
def panel() -> pl.DataFrame:
    return pl.read_parquet(PANEL_PATH)


@pytest.fixture(scope="module")
def events() -> pl.DataFrame:
    return pl.read_parquet(SETTINGS.curated_dir / "ca_events.parquet")


def test_adjusted_closes_match_yahoo(panel: pl.DataFrame) -> None:
    rows = _read_fixture("yahoo_prices.csv")
    assert len(rows) > 100
    checked = 0
    misses: list[str] = []
    for row in rows:
        d = date.fromisoformat(row["trade_date"])
        cutoff = YAHOO_PRICE_EXCEPTIONS.get(row["symbol"])
        if cutoff is not None and d < cutoff:
            continue
        ours = panel.filter((pl.col("canon_symbol") == row["symbol"]) & (pl.col("trade_date") == d))
        if ours.is_empty():
            misses.append(f"{row['symbol']} {row['trade_date']}: no panel row")
            continue
        yahoo = float(row["yahoo_close"])
        dev = abs(ours["adj_close"][0] / yahoo - 1)
        if dev > PRICE_REL_TOL:
            misses.append(f"{row['symbol']} {row['trade_date']}: dev {dev:.2%}")
        checked += 1
    assert checked > 100
    assert not misses, f"{len(misses)} price deviations: {misses[:10]}"


def test_ca_factors_match_yahoo_splits(events: pl.DataFrame) -> None:
    # panel starts 2010-01-04; Yahoo's split history reaches the 1990s.
    # Yahoo lists a same-day bonus and split as separate rows: combine them,
    # since our adjuster stores one multiplied factor per (symbol, ex_date).
    combined: dict[tuple[str, str], float] = {}
    for r in _read_fixture("yahoo_splits.csv"):
        if r["ex_date"] >= "2010-02-01":
            key = (r["symbol"], r["ex_date"])
            combined[key] = combined.get(key, 1.0) * float(r["yahoo_ratio"])
    rows: list[dict[str, str | float]] = [
        {"symbol": s, "ex_date": d, "yahoo_ratio": ratio}
        for (s, d), ratio in sorted(combined.items())
    ]
    assert len(rows) >= 20
    matched = 0
    problems: list[str] = []
    for row in rows:
        exd = date.fromisoformat(str(row["ex_date"]))
        if (row["symbol"], exd) in YAHOO_SPLIT_EXCEPTIONS:
            matched += 1
            continue
        want = 1.0 / float(row["yahoo_ratio"])
        near = events.filter(
            (pl.col("canon_symbol") == row["symbol"])
            & (
                pl.col("ex_date").is_between(
                    exd - timedelta(days=EX_DATE_SLACK_DAYS),
                    exd + timedelta(days=EX_DATE_SLACK_DAYS),
                )
            )
        )
        if near.is_empty():
            problems.append(f"{row['symbol']} {exd}: no event (want {want:.3f})")
            continue
        got = near["factor"][0]
        if abs(got / want - 1) > FACTOR_REL_TOL:
            problems.append(f"{row['symbol']} {exd}: factor {got:.4f} vs yahoo {want:.4f}")
        else:
            matched += 1
    # Yahoo occasionally records events NSE classifies differently; demand a
    # high match rate and zero factor disagreements among matches.
    assert matched / len(rows) >= 0.9, f"match rate {matched}/{len(rows)}; {problems[:10]}"
    assert not [p for p in problems if "vs yahoo" in p], problems[:10]
